//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: trapezoid Created :
// Initializer: trapezoid.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "trapezoidFunctionMap.h"
#include  <XSFunctions/Utilities/XSCall.h>
#include  <XSFunctions/Utilities/XSModelFunction.h>

extern "C" int Trapezoid_Init(Tcl_Interp* tclInterp);
extern "C" int Trapezoid_SafeInit(Tcl_Interp* tclInterp);

int Trapezoid_Init(Tcl_Interp* tclInterp)
{
        return Trapezoid_SafeInit(tclInterp);
}

int Trapezoid_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "trapezoid";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        XSModelFunction::updateComponentList
              ("/Users/aoki/.GIT/ast_tools/xspec_models/obsolete/trapezoid_v3_cpp_hmake/model.dat");
        createtrapezoidFunctionMap();
        return TCL_OK;

}

