//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: trapezoid
// Function body: trapezoidFunctionMap.cxx

#include    "trapezoidFunctionMap.h"

#include    <XSFunctions/Utilities/XSModelFunction.h>
#include    <XSFunctions/Utilities/XSCall.h>

void 
createtrapezoidFunctionMap()
{


	XSModelFunction::addFunctionPointer( "trapezoid",  new XSCall<xsccCall>(trapezoidmod) );

}
