//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: trapezoid
// Function header: trapezoidFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <XSFunctions/Utilities/funcType.h>

class    XSCallBase;

void  createtrapezoidFunctionMap();

extern "C"  {


	xsccCall     trapezoidmod;
}


#endif
