SUBROUTINE TRAPEZOID_INIT BIND(C, NAME="Trapezoid_Init")
  PRINT *, 'Trapezoid model initialized'
  RETURN
END SUBROUTINE TRAPEZOID_INIT

! 既存のサブルーチン
SUBROUTINE TRAPEZOIDMODEL(EAR, NE, PARAM, IFLAG, PHOTAR, PHOTER)
  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NE, IFLAG
  DOUBLE PRECISION, INTENT(IN)  :: EAR(NE+1), PARAM(5)
  DOUBLE PRECISION, INTENT(OUT) :: PHOTAR(NE), PHOTER(NE)
  DOUBLE PRECISION :: E1, E2, E3, E4, AMP
  INTEGER :: I

  ! パラメータの取得
  E1 = PARAM(1)
  E2 = PARAM(2)
  E3 = PARAM(3)
  E4 = PARAM(4)
  AMP = PARAM(5)

  ! エネルギー範囲ごとの強度計算
  DO I = 1, NE
    IF (EAR(I) >= E1 .AND. EAR(I) < E2) THEN
      PHOTAR(I) = AMP * (EAR(I) - E1) / (E2 - E1)
    ELSE IF (EAR(I) >= E2 .AND. EAR(I) < E3) THEN
      PHOTAR(I) = AMP
    ELSE IF (EAR(I) >= E3 .AND. EAR(I) < E4) THEN
      PHOTAR(I) = AMP * (E4 - EAR(I)) / (E4 - E3)
    ELSE
      PHOTAR(I) = 0.0D0
    END IF
  END DO

  RETURN
END SUBROUTINE TRAPEZOIDMODEL
