//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: trapezoid_mod Created :
// Initializer: trapezoid_mod.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "trapezoid_modFunctionMap.h"
#include  <XSFunctions/Utilities/XSCall.h>
#include  <XSFunctions/Utilities/XSModelFunction.h>

extern "C" int Trapezoid_mod_Init(Tcl_Interp* tclInterp);
extern "C" int Trapezoid_mod_SafeInit(Tcl_Interp* tclInterp);

int Trapezoid_mod_Init(Tcl_Interp* tclInterp)
{
        return Trapezoid_mod_SafeInit(tclInterp);
}

int Trapezoid_mod_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "trapezoid_mod";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        XSModelFunction::updateComponentList
              ("/Users/aoki/.GIT/ast_tools/xspec_models/trapezoid_v2/model.dat");
        createtrapezoid_modFunctionMap();
        return TCL_OK;

}

