//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: trapezoid_mod
// Function header: trapezoid_modFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <XSFunctions/Utilities/funcType.h>

class    XSCallBase;

void  createtrapezoid_modFunctionMap();

extern "C"  {


	xsccCall     trapezoidmod;
}


#endif
