//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: trapezoid_mod
// Function body: trapezoid_modFunctionMap.cxx

#include    "trapezoid_modFunctionMap.h"

#include    <XSFunctions/Utilities/XSModelFunction.h>
#include    <XSFunctions/Utilities/XSCall.h>

void 
createtrapezoid_modFunctionMap()
{


	XSModelFunction::addFunctionPointer( "trapezoid_mod", new XSCall<xsccCall>(trapezoidmod) );

}
